In [10]:
from random import random,seed,randint
from pprint import pprint
def initialize(n_inputs,n_hidden,n_output):
    network=[]
    hidden_layer=[{'w':[random() for i in range(n_inputs+1)]} for i in range(n_hidden)] 
    network.append(hidden_layer)
    output_layer=[{'w':[random() for i in range(n_hidden+1)]} for i in range(n_output)]
    network.append(output_layer)
    return network
def activate(w,i):
    activation=w[-1] 
    for x in range(len(w)-1):
        activation+=w[x]*i[x] 
        return activation 
from math import exp
def sigmoid(a):
    return 1/(1+exp(-a))
def forward_prop(network,row):
    inputs=row
    for layer in network:
        new_inputs=[]
        for neuron in layer:
            activation=activate(neuron['w'],inputs) 
            neuron['output']=sigmoid(activation) 
            new_inputs.append(neuron['output']) 
        inputs=new_inputs 
    return inputs
def sigmoid_derivative(output):
    return output * (1-output) 
def backprop(network,expected): 
    for i in reversed(range(len(network))): 
        layer=network[i] 
        errors=[] 
        if i!=len(network)-1: 
            for j in range(len(layer)):
                error=0 
                for neuron in network[i+1]:
                    error+=(neuron['w'][j]*neuron['delta'])
                errors.append(error)
        else:
                for j in range(len(layer)):
                    neuron=layer[j]
                    errors.append(expected[j]-neuron['output']) 
        for j in range(len(layer)):
                neuron=layer[j]
                neuron['delta']=errors[j]*sigmoid_derivative(neuron['output']) 
def update_weights(network,row,lrate):
    for i in range(len(network)):
        inputs=row[:-1]
        if i!=0: 
            inputs=[neuron['output'] for neuron in network[i-1]]
            for neuron in network[i]:
                for j in range(len(inputs)):
                    neuron['w'][j]+=lrate*neuron['delta']*inputs[j] 
                    neuron['w'][-1]+=lrate*neuron['delta'] 
def train_network(network,train,lrate,epochs,n_output):
    for epoch in range(epochs):
        sum_err=0
        for row in train:
            outputs=forward_prop(network,row)
            expected=[0 for i in range(n_output)]
            expected[row[-1]]=1
            sum_err+=sum([(expected[i]-outputs[i])**2 for i in range(len(expected))])
            backprop(network,expected)
            update_weights(network,row,lrate)
        print('epoch=%d, lrate=%.3f,error=%.3f'%(epoch,lrate,sum_err))
seed(1)
data=[[2.7810836,2.550537003,0],
      [1.465489372,2.362125076,0],
      [3.396561688,4.400293529,0],
      [1.38807019,1.850220317,0],
      [3.06407232,3.005305973,0],
      [7.627531214,2.759262235,1],
      [5.332441248,2.088626775,1],
      [6.922596716,1.77106367,1],
      [8.675418651,-0.242068655,1],
      [7.673756466,3.508563011,1]] 
n_inputs=len(data[0])-1
n_outputs=len(set(row[-1] for row in data))
network=initialize(n_inputs,2,n_outputs)
pprint(network)
train_network(network,data,0.5,20,n_outputs)
for layer in network:
    pprint(layer)

[[{'w': [0.13436424411240122, 0.8474337369372327, 0.763774618976614]},
  {'w': [0.2550690257394217, 0.49543508709194095, 0.4494910647887381]}],
 [{'w': [0.651592972722763, 0.7887233511355132, 0.0938595867742349]},
  {'w': [0.02834747652200631, 0.8357651039198697, 0.43276706790505337]}]]
epoch=0, lrate=0.500,error=5.440
epoch=1, lrate=0.500,error=5.333
epoch=2, lrate=0.500,error=5.353
epoch=3, lrate=0.500,error=5.378
epoch=4, lrate=0.500,error=5.391
epoch=5, lrate=0.500,error=5.394
epoch=6, lrate=0.500,error=5.392
epoch=7, lrate=0.500,error=5.388
epoch=8, lrate=0.500,error=5.382
epoch=9, lrate=0.500,error=5.376
epoch=10, lrate=0.500,error=5.370
epoch=11, lrate=0.500,error=5.363
epoch=12, lrate=0.500,error=5.356
epoch=13, lrate=0.500,error=5.350
epoch=14, lrate=0.500,error=5.343
epoch=15, lrate=0.500,error=5.337
epoch=16, lrate=0.500,error=5.330
epoch=17, lrate=0.500,error=5.323
epoch=18, lrate=0.500,error=5.317
epoch=19, lrate=0.500,error=5.310
[{'delta': 0.007075129766006115,
  'output

In [6]:
import numpy as np

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)     
y = np.array(([92], [86], [89]), dtype=float)           

X = X/np.amax(X, axis=0)        
y = y/100                   

In [7]:
class Neural_Network(object):
    def __init__(self):
                            # Parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
                             # Weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)        # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)       # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
                             #forward propagation through our network
        self.z = np.dot(X, self.W1)               # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z)            # activation function
        self.z3 = np.dot(self.z2, self.W2)        # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3)                 # final activation function
        return o 

    def sigmoid(self, s):
        return 1/(1+np.exp(-s))     # activation function 

    def sigmoidPrime(self, s):
        return s * (1 - s)          # derivative of sigmoid
    
    def backward(self, X, y, o):
                                    # backward propgate through the network
        self.o_error = y - o        # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to 
        self.z2_error = self.o_delta.dot(self.W2.T)    # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error
        self.W1 += X.T.dot(self.z2_delta)       # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta)  # adjusting second set (hidden --> output) weights

    def train (self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

In [8]:
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
    print ("\nInput: \n" + str(X))
    print ("\nActual Output: \n" + str(y)) 
    print ("\nPredicted Output: \n" + str(NN.forward(X)))
    print ("\nLoss: \n" + str(np.mean(np.square(y - NN.forward(X)))))     # mean sum squared loss)
    NN.train(X, y)


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.75499172]
 [0.76305549]
 [0.74773908]]

Loss: 
0.018954713375236423

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.76734059]
 [0.7741137 ]
 [0.76024339]]

Loss: 
0.01583937737844524

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.77801508]
 [0.78366169]
 [0.7710492 ]]

Loss: 
0.013378848932098444

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.78731951]
 [0.79197803]
 [0.78046616]]

Loss: 
0.011409587622909242

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]


Loss: 
0.0006077529454878938

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.8836098 ]
 [0.87811651]
 [0.8780264 ]]

Loss: 
0.0005986071884107386

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.88400755]
 [0.87846938]
 [0.87843199]]

Loss: 
0.0005901312104483115

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.88438934]
 [0.87880776]
 [0.8788214 ]]

Loss: 
0.0005822707551943576

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.88475593]
 [0.87913232]
 [0.87919541]]

Loss: 
0.0005749763915136269

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actu

 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.8930494 ]
 [0.88618069]
 [0.88771688]]

Loss: 
0.0004723254270452356

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89310612]
 [0.88622209]
 [0.88777641]]

Loss: 
0.00047194091720574154

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89316107]
 [0.88626184]
 [0.88783413]]

Loss: 
0.000471567883007973

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89321428]
 [0.88630001]
 [0.8878901 ]]

Loss: 
0.0004712055947369451

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89326583]
 [0.88633664]
 [0.


Predicted Output: 
[[0.89447738]
 [0.88698789]
 [0.88925605]]

Loss: 
0.00046010123870257304

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89449124]
 [0.88698989]
 [0.88927199]]

Loss: 
0.0004598936851089689

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89450473]
 [0.88699156]
 [0.88928755]]

Loss: 
0.0004596868171578127

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89451786]
 [0.88699289]
 [0.88930274]]

Loss: 
0.00045948060192636337

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89453063]
 [0.8869939 ]
 [0.88931756]]

Loss: 
0.00045927500854901017

Input: 
[[0.66666667 1.

 [0.88986627]]

Loss: 
0.00044640985451517616

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89495659]
 [0.88667351]
 [0.88987133]]

Loss: 
0.0004462215962252101

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.8949598 ]
 [0.88666597]
 [0.88987635]]

Loss: 
0.00044603349642777555

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89496298]
 [0.8866584 ]
 [0.88988134]]

Loss: 
0.0004458455546424537

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89496611]
 [0.8866508 ]
 [0.88988628]]

Loss: 
0.00044565777041115573

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         

 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89507096]
 [0.88633164]
 [0.89006194]]

Loss: 
0.00043827202877587873

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89507324]
 [0.88632345]
 [0.89006597]]

Loss: 
0.0004380904619393396

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89507552]
 [0.88631526]
 [0.89006998]]

Loss: 
0.00043790904276807397

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89507779]
 [0.88630706]
 [0.89007398]]

Loss: 
0.00043772777111672517

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89508005]
 [0.88629886]
 


Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89517339]
 [0.88593727]
 [0.8902461 ]]

Loss: 
0.0004297210330813539

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89517543]
 [0.88592908]
 [0.8902498 ]]

Loss: 
0.00042954640299715154

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89517746]
 [0.8859209 ]
 [0.8902535 ]]

Loss: 
0.00042937191430315663

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89517949]
 [0.88591271]
 [0.89025719]]

Loss: 
0.00042919756687542424

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89518151]
 [0.88590453]
 [0.89026088]]

Loss: 
0.00


Predicted Output: 
[[0.89531036]
 [0.88538045]
 [0.89049505]]

Loss: 
0.0004179968565145812

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89531232]
 [0.88537252]
 [0.89049859]]

Loss: 
0.0004178316970367281

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89531427]
 [0.8853646 ]
 [0.89050212]]

Loss: 
0.0004176666706353054

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89531623]
 [0.88535668]
 [0.89050565]]

Loss: 
0.0004175017771931824

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89531818]
 [0.88534876]
 [0.89050918]]

Loss: 
0.0004173370165932992

Input: 
[[0.66666667 1.   

 [0.89077581]]

Loss: 
0.0004050402703437717

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.8954692 ]
 [0.88474448]
 [0.89077921]]

Loss: 
0.00040488551864557355

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89547112]
 [0.8847369 ]
 [0.89078261]]

Loss: 
0.0004047308908439185

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89547304]
 [0.88472932]
 [0.89078601]]

Loss: 
0.00040457638682938046

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89547496]
 [0.88472175]
 [0.89078941]]

Loss: 
0.00040442200649259285

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         


Predicted Output: 
[[0.89564433]
 [0.88406483]
 [0.89108565]]

Loss: 
0.0003911644607453857

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89564621]
 [0.88405763]
 [0.89108891]]

Loss: 
0.0003910207752348303

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.8956481 ]
 [0.88405044]
 [0.89109217]]

Loss: 
0.0003908772038365381

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89564998]
 [0.88404325]
 [0.89109543]]

Loss: 
0.00039073374644954035

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89565187]
 [0.88403607]
 [0.89109869]]

Loss: 
0.0003905904029729711

Input: 
[[0.66666667 1.  


Predicted Output: 
[[0.89578463]
 [0.88353616]
 [0.89132623]]

Loss: 
0.00038069799775774317

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89578648]
 [0.88352926]
 [0.89132938]]

Loss: 
0.0003805625963851113

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89578834]
 [0.88352236]
 [0.89133253]]

Loss: 
0.000380427301793542

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89579019]
 [0.88351547]
 [0.89133568]]

Loss: 
0.00038029211388852276

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89579204]
 [0.88350858]
 [0.89133883]]

Loss: 
0.00038015703257563284

Input: 
[[0.66666667 1. 

 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89589517]
 [0.88312893]
 [0.89151289]]

Loss: 
0.0003727597243315994

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.895897  ]
 [0.88312226]
 [0.89151596]]

Loss: 
0.0003726305653799184

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89589883]
 [0.88311559]
 [0.89151903]]

Loss: 
0.0003725015076849459

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89590065]
 [0.88310892]
 [0.89152209]]

Loss: 
0.0003723725511570915

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89590248]
 [0.88310226]
 [0.


Predicted Output: 
[[0.89602213]
 [0.88267076]
 [0.89172431]]

Loss: 
0.0003639583009554936

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89602393]
 [0.88266435]
 [0.89172728]]

Loss: 
0.0003638360179292782

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89602573]
 [0.88265793]
 [0.89173025]]

Loss: 
0.0003637138300781012

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89602753]
 [0.88265153]
 [0.89173322]]

Loss: 
0.0003635917373178256

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89602932]
 [0.88264512]
 [0.89173619]]

Loss: 
0.00036346973956438196

Input: 
[[0.66666667 1.  


Loss: 
0.00035539224934559615

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89615217]
 [0.88221162]
 [0.89193769]]

Loss: 
0.00035527660831123593

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89615393]
 [0.88220546]
 [0.89194057]]

Loss: 
0.0003551610565836957

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.8961557 ]
 [0.8821993 ]
 [0.89194344]]

Loss: 
0.0003550455940841307

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89615746]
 [0.88219315]
 [0.89194631]]

Loss: 
0.00035493022073376687

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

A

 [0.89213846]]

Loss: 
0.000347289733519746

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89627798]
 [0.88177664]
 [0.89214124]]

Loss: 
0.00034718032525091273

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89627971]
 [0.88177072]
 [0.89214402]]

Loss: 
0.0003470710007911879

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89628144]
 [0.8817648 ]
 [0.8921468 ]]

Loss: 
0.00034696176006673114

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89628317]
 [0.88175889]
 [0.89214958]]

Loss: 
0.0003468526030037495

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89639284]
 [0.88138714]
 [0.89232466]]

Loss: 
0.0003400372414111481

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89639454]
 [0.88138143]
 [0.89232735]]

Loss: 
0.0003399333672510682

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89639624]
 [0.88137573]
 [0.89233004]]

Loss: 
0.0003398295720284991

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89639793]
 [0.88137003]
 [0.89233274]]

Loss: 
0.0003397258556740302

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [